language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- mvn install
script:
- "./aws-upload.sh"
env:
  global:
  - AWS_DEFAULT_REGION=eu-central-1
  - secure: D5ZOdUu68Zq3MJCxwLL6X5BDe+GnfgrjOv+8Nsu0LSjli9/Y2nwaF7JAEC4lCJZ1fF62Iq+4qK2IgYg5vegSs/lXuEMcwFZst96tIT1RCX6WAc4TaE566HbVStP7KWewF+DI3A1mPpprc0n5ROGVUD6n2atlEHFXhBHEX2flIaZrWxFCca/smF4O8VlyxsmI9Ua1ueOyvAZzg9idnbWHZThiB07HstsHd2tNu/cxZ+LGrsjsDC76FIPKG2EWfkoSn99Tq9o6C90UeiFxvoDHdg1uuvbb+rcaIbnjiCM26r54BudGF0wI+Cf0hGl+e3hFIkgddS12DanjH0n4YuP+2vIbjW9mtpTnDZzCKf4uIWE6Ll8pqbYDzfWCILlOgMO8QOI4EqFJ3AAsY1V/Cw8JRMz10L50pPTpAI9n7k7MsNeI39OMbJJLCcQu7Vz3gUyVWzKrN3uLeKNYpB9nvTJYlkBMTnUY0yT94Wx0w+QHxYqfxEYFfS7fW9nikeXlnxuk+IvW9DGhveSHbjvGWMQ8TWjWVeNyKQuzjN6xQYPUKDpjcBZlrhMaH717da3q4CbeeVZkUYDFLovcV2WhetMI9wWylrL8AHnIkyAiyULt/Vsy6CJLPBYOcBUXvfrksxeB6cMWCqy4HykGR217Ouo0xMFxYHUbrOANqKdx5fMiG3Y=
  - secure: rEeXKQ94fdDL4m0g6w/cOWPfO20lVMQS/I0WXZVgt3ETBdO6q09CeLAv6Z6/29YVn3YSzzEzsC+1ua5sCsL+J2Z9c5Ka1hrPytv4mB5hJZ0guxONAxx4a1+ybXrEZ/zdOIDgz+JYAo9UovxF04TArAZeMqWkaQ80J1yyVSPraCh5rVaKW2XPFsB5OT+Aab5qqrowX5YTp+AmDcKCJ3d0JtLYpmXrLLlxLF1tYIgkMRqtCMb/nRcQ+C1ZW0QJBLseewzgI+mXP6j6V7Huzf0pRNFQDNoZNhwxh/SpUEYM2VBOIIaMHmsE+O+OSa1AdMWNgUeOjER/jNp/H0+owjzxL8J1kAAK6IzWMuq7vnZhY5lTjAFS1lF2YnEIr1RD0gXEZzj+Ll9osvM0hD0dAuZp0v7HvP1P/srSmzKz03zdvutPp680qyHwwjRbc40rzeiroNZ/NLsrF+sM8T7fR10+OEIii2g4d96+Z8lQGgTvRSR2ipFp6perGd+xg0pa0Hscbg3zpDnwrkK/wJqeMejXtK42GEvDraA3DvuD4GQJ4sEnJO4a9uBKkCZ+Ew11hbq353oavwIlrtu6bi6pc++mmNhXmds7KHdUnpHsVm+kUNflbozJXHGH0YxUWNC6fINpdU3dy7N1zgdlyeovv1kplavcw9AXvCdGZe9QUbOn6Mk=
